@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;
:AddressBookParser parses command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid addclient command string])
    :Create new client;
    :Add client to persons in AddressBook;
    stop
else ([else])
    :Display error message;
    stop
@enduml
