@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package "Person Classes" as ModelPackage <<Rectangle>>{
Class "{abstract}\nPerson" as Person
Class Lead
Class Client
}
Class HiddenOutside #FFFFFF
HiddenOutside ..> Person

Lead -up-|> Person
Client -up-|> Person
@enduml
